from django.contrib import admin
from .models import *
# Register your models here.

admin.site.register(Apps)
admin.site.register(CallList)
admin.site.register(Cat)
admin.site.register(Comment)
admin.site.register(FbPage)
admin.site.register(HotlineNumbers)
admin.site.register(Post)
admin.site.register(Reg)
admin.site.register(Service)
admin.site.register(Shop)
admin.site.register(TermPolicy)
admin.site.register(Users)
admin.site.register(ViewList)
# admin.site.register(AuthGroup)
# admin.site.register(AuthGroupPermissions)
# admin.site.register(AuthPermission)
# admin.site.register(AuthUser)
# admin.site.register(AuthUserGroups)
# admin.site.register(AuthGroupPermissions)
# admin.site.register(DjangoAdminLog)
# admin.site.register(DjangoContentType)
# admin.site.register(DjangoMigrations)
# admin.site.register(DjangoSession)
