# Generated by Django 5.1.4 on 2025-05-09 07:49

from django.db import migrations,models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_apps_authgroup_authgrouppermissions_authpermission_and_more'),
    ]

    operations =[
        migrations.AlterField(
            model_name='cat',
            name='yes_service',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='cat',
            name='yes_shop',
            field=models.BooleanField(default=False),
        ),
    ]