# Generated by Django 5.1.4 on 2025-10-29 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_auto_20250509_1349'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about', models.TextField(blank=True, null=True)),
                ('founders', models.TextField(blank=True, null=True)),
                ('sponsors', models.TextField(blank=True, null=True)),
                ('office_address', models.TextField(blank=True, null=True)),
                ('contact', models.TextField(blank=True, null=True)),
                ('goals', models.TextField(blank=True, null=True)),
                ('quote', models.TextField(blank=True, null=True)),
                ('last_updated', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'about_info',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CallListBackup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('call_id', models.IntegerField()),
                ('call_time', models.DateTimeField()),
                ('call_user_id', models.IntegerField()),
                ('user_id', models.IntegerField()),
            ],
            options={
                'db_table': 'call_list_backup',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DesCat',
            fields=[
                ('des_cat_id', models.AutoField(primary_key=True, serialize=False)),
                ('des_cat_name', models.CharField(max_length=255)),
                ('des_cat_status', models.IntegerField()),
            ],
            options={
                'db_table': 'des_cat',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Description',
            fields=[
                ('des_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.IntegerField()),
                ('time', models.DateTimeField(blank=True, null=True)),
                ('des', models.TextField()),
                ('des_photo', models.CharField(blank=True, max_length=255, null=True)),
                ('des_view', models.IntegerField()),
                ('des_com', models.IntegerField()),
            ],
            options={
                'db_table': 'description',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FavoriteUsers',
            fields=[
                ('fav_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.IntegerField()),
                ('fav_users', models.IntegerField()),
            ],
            options={
                'db_table': 'favorite_users',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('loc_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.IntegerField(unique=True)),
                ('lat', models.CharField(max_length=50)),
                ('lon', models.CharField(max_length=50)),
                ('address', models.TextField()),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'location',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Notifications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('type', models.CharField(max_length=7)),
                ('detail_user', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('is_read', models.IntegerField(blank=True, null=True)),
                ('detail_post_id', models.IntegerField()),
                ('service_id', models.IntegerField()),
                ('shop_id', models.IntegerField()),
                ('is_service', models.IntegerField()),
            ],
            options={
                'db_table': 'notifications',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Subscribers',
            fields=[
                ('sub_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.IntegerField()),
                ('reg_id', models.IntegerField()),
                ('cat_id', models.IntegerField()),
                ('type', models.CharField(max_length=255)),
                ('last_pay', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'subscribers',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ThoughtComment',
            fields=[
                ('com_id', models.AutoField(primary_key=True, serialize=False)),
                ('com_text', models.TextField()),
                ('com_time', models.DateTimeField(blank=True, null=True)),
                ('com_user_id', models.IntegerField()),
                ('des_id', models.IntegerField()),
            ],
            options={
                'db_table': 'thought_comment',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UserDeactivations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField()),
                ('deactivated_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'user_deactivations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UserReferrals',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('referral_id', models.CharField(max_length=8)),
                ('referrer_user_id', models.IntegerField()),
                ('referred_user_id', models.IntegerField(unique=True)),
                ('referred_cat_id', models.IntegerField()),
                ('points', models.IntegerField()),
                ('payment_status', models.CharField(max_length=10)),
                ('created_at', models.DateTimeField()),
                ('verification', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'user_referrals',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='MembersMember',
        ),
        migrations.AlterModelOptions(
            name='hotlinenumbers',
            options={'managed': False},
        ),
    ]
