# Generated by Django 5.1.4 on 2026-07-18 18:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0004_aboutinfo_calllistbackup_descat_description_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BroadcastNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('target_cat_ids', models.TextField(default='[]')),
                ('sent_count', models.IntegerField(default=0)),
                ('failed_count', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('sending', 'Sending'), ('sent', 'Sent'), ('failed', 'Failed')], default='draft', max_length=20)),
                ('created_by', models.CharField(default='admin', max_length=100)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'broadcast_notifications',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ContactInfo',
            fields=[
                ('id', models.IntegerField(default=1, primary_key=True, serialize=False)),
                ('phone', models.CharField(blank=True, default='', max_length=50)),
                ('email', models.CharField(blank=True, default='', max_length=100)),
                ('address', models.CharField(blank=True, default='', max_length=255)),
                ('website', models.CharField(blank=True, default='', max_length=255)),
                ('facebook', models.CharField(blank=True, default='', max_length=255)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'contact_info',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DeletedAccount',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('original_user_id', models.IntegerField()),
                ('reg_id', models.IntegerField(blank=True, null=True)),
                ('phone', models.CharField(max_length=20)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('cat_id', models.IntegerField(blank=True, null=True)),
                ('photo', models.CharField(blank=True, max_length=500, null=True)),
                ('deleted_by', models.CharField(max_length=10)),
                ('reason', models.TextField(blank=True, null=True)),
                ('delete_time', models.DateTimeField()),
            ],
            options={
                'db_table': 'deleted_accounts',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DesCatSuggestion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('suggestion_text', models.CharField(max_length=255)),
                ('sort_order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'des_cat_suggestion',
                'ordering': ['des_sub_cat_id', 'sort_order'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DesSubCat',
            fields=[
                ('des_sub_cat_id', models.AutoField(primary_key=True, serialize=False)),
                ('name_bn', models.CharField(max_length=120)),
                ('name_en', models.CharField(blank=True, max_length=120, null=True)),
                ('emoji', models.CharField(blank=True, max_length=10, null=True)),
                ('sort_order', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'des_sub_cat',
                'ordering': ['des_cat_id', 'sort_order'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='NotificationRule',
            fields=[
                ('rule_id', models.AutoField(primary_key=True, serialize=False)),
                ('rule_name', models.CharField(max_length=255)),
                ('des_cat_id', models.IntegerField()),
                ('des_sub_cat_id', models.IntegerField(default=0)),
                ('target_cat_ids', models.TextField(default='[]')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'notification_rules',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='NotificationSendLog',
            fields=[
                ('log_id', models.AutoField(primary_key=True, serialize=False)),
                ('trigger_type', models.CharField(choices=[('post', 'Post'), ('broadcast', 'Broadcast'), ('new_user', 'New User'), ('subscription', 'Subscription')], max_length=20)),
                ('trigger_id', models.IntegerField()),
                ('triggered_by', models.IntegerField(default=0)),
                ('rule_id', models.IntegerField(blank=True, null=True)),
                ('title', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('target_cats', models.TextField(blank=True, null=True)),
                ('sent_count', models.IntegerField(default=0)),
                ('failed_count', models.IntegerField(default=0)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'notification_send_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SubscriptionSettings',
            fields=[
                ('id', models.IntegerField(default=1, primary_key=True, serialize=False)),
                ('call_threshold', models.IntegerField(default=50)),
                ('view_threshold', models.IntegerField(default=100)),
            ],
            options={
                'db_table': 'subscription_settings',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AdminProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allowed_pages', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='admin_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'admin_profile',
                'managed': True,
            },
        ),
    ]
